export PageFrame from './PageFrame/PageFrame'
export ConfettiHero from './ConfettiHero/ConfettiHero'
export Candybox from './Candybox/'
export Letterbox from './Letterbox/'
export FloatingBox from './FloatingBox/'